name: aqua_lens
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flex_color_scheme: ^7.3.1
  flutter_animate: ^4.5.0
  dio: ^5.6.0
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  video_player: ^2.9.1
  equatable: ^2.0.5
  path_provider: ^2.1.4
  camera: ^0.11.0+2
  permission_handler: ^11.3.1
  crystal_navigation_bar: ^1.0.0
  toasty_box: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/output/